### ISSUE TITLE
access_token query string on resource.get_legend.url causes legend image to not appear

### ISSUE THREAD

**Issue by senoadiw** [ismailsunni/geonode_qgis_server#11]
* geonode_qgis_server version: 0.1.1
* GeoNode version: 2.5.10
* Python version:
* Operating System:

### Description

On recent GeoNode versions, for logged in users the access_token query string is appended to the resource.get_legend.url in https://github.com/GeoNode/geonode/blob/47f2a42ff60be0c0c427b78df5e73a411ac2b2e1/geonode/layers/templates/layers/layer_detail.html#L430

For anonymous users the legend appears fine. Here is what it looks like as admin user:

![docker-geonode-qgis legend](https://cloud.githubusercontent.com/assets/1198399/22328947/7d1f6ff4-e3f1-11e6-84e8-2c8cc0b7646a.png)

Thanks

**Comment by ismailsunni** [comment]
Thanks @senoadiw for the report.
Well, I haven't tested with the current version of geonode. It seems, they added new code that geoserver-specific. But it doesn't cover QGIS Server, unfortunatelly.

**Comment by timlinux** [comment]
@ismailsunni we should write a regex to strip off the access token before passing the request downstream to QGIS server?

**Comment by ismailsunni** [comment]
Hmm, after looked at the code again, the access token should be ignored since it's a GET parameter and the legend should have been shown.

@timlinux yes, that can work

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#189

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#190
