### ISSUE TITLE
Write tests to make sure it is still working with current Geonode

### ISSUE THREAD

**Issue by lucernae** [ismailsunni/geonode_qgis_server#16]
# Intro

This package is about integrating qgis-server backend to geonode.
We don't have any proper integration tests yet, so it would be good to have some.
As this is a django app, please create appropriate django test.

The following context is what I have in mind to be tested:

- Test uploading layer works with QGIS-Server
- Make sure zip download url works
- Make sure legend works
- Make sure map thumbnails works
- Other functionality in views were properly tested

# Dependencies

- Geonode latest release (currently latest 2.6)
- QGIS-Server LTR 2.14
- Django 1.8

@boney-bun if you're not yet familiar with GIS related terms (like WMS, WFS, OGR), you can asks @gubuntu here :D. He's the GIS master.

**Comment by Gustry** [comment]
Do we plan to add tests to the main Geonode repo?
I guess yes as the plan is to merge qgis server app into geonode.

**Comment by lucernae** [comment]
> Do we plan to add tests to the main Geonode repo?

Not sure. But if this app is merged into geonode, then yes, we should.

For now, I'm planning to just use travis or something in this repo.

**Comment by boney-bun** [comment]
I found a sample of integration test from docker-geosafe repo. the integration test is developed by OSGeo. Could this file be useful for the integration test? Please refers to this file: https://github.com/kartoza/geonode/blob/67b77489c249bc88b0c6262941ee5e3f2d49613c/geonode/tests/integration.py

**Comment by gubuntu** [comment]
This issue was moved to kartoza/geonode#184
