### ISSUE TITLE
Update pypi package

### ISSUE THREAD

**Issue by senoadiw** [ismailsunni/geonode_qgis_server#8]
* geonode_qgis_server version: 0.1.0
* GeoNode version: 2.5.7
* Python version: 2.7.9
* Operating System: Ubuntu 16.04

### Description

The pypi package @ https://pypi.python.org/pypi/geonode_qgis_server needs to be updated to include #3.

### What I Did

geonode_qgis_server breaks GeoNode that uses a custom DJANGO_SETTINGS_MODULE like my_geonode.settings.

**Comment by lucernae** [comment]
@ismailsunni I think I already made a commit addressing this. So, you can just update the pypi package.

**Comment by ismailsunni** [comment]
Uploaded : https://pypi.python.org/pypi/geonode_qgis_server/0.1.1
